name: dynamic_call
description: Dynamic Call framework, including API calls integrations (HTTP, RESTful).
version: 1.0.18
homepage: https://github.com/gmpassos/dynamic_call

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mercury_client: ^2.0.0-nullsafety.1
  swiss_knife: ^3.0.1
  json_object_mapper: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
  #test_coverage: ^0.4.3

#dependency_overrides:
#  mercury_client:
#    path: ../mercury_client
#  swiss_knife:
#    path: ../swiss_knife
#  json_object_mapper:
#    path: ../json_object_mapper

