name: dynamic_call
description: Dynamic Call framework, including API calls integrations (HTTP, RESTful).
version: 1.0.9
homepage: https://github.com/gmpassos/dynamic_call

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mercury_client: ^1.1.7
    #path: ../mercury_client
  swiss_knife: ^2.4.1
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
