name: dynamic_call
description: Dynamic Call framework, including API calls integrations (HTTP, RESTful).
version: 1.0.11
homepage: https://github.com/gmpassos/dynamic_call

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mercury_client: ^1.1.9
    #path: ../mercury_client
  swiss_knife: ^2.5.5
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  test_coverage: ^0.4.2
